# Generated by Django 5.2.5 on 2025-11-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_plan_user_plan_end_date_user_plan_start_date_and_more'),
        ('chatbot', '0010_plan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
