# Generated by Django 5.2.5 on 2025-11-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_delete_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrecord',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
