# Generated by Django 5.2.5 on 2025-11-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_plan_user_plan_end_date_user_plan_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.AddField(
            model_name='user',
            name='is_plan_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_type',
            field=models.CharField(choices=[('freebie', 'Freebie'), ('premium', 'Premium')], default='freebie', max_length=20),
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
