# Generated by Django 5.2.5 on 2025-11-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_plan_user_is_plan_paid_user_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
