# Generated by Django 5.2.5 on 2025-11-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
