# Generated by Django 5.2.5 on 2025-11-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_total_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_time',
            field=models.IntegerField(default=600),
        ),
    ]
